import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import Navbar from "@/components/navbar";
import Hero from "@/components/hero";
import Social from "@/components/social";
import Form from "@/components/form";
import Footer from "@/components/footer";

export default function Contact() {
  return (
    <>
      <Head>
        <title>Portfolio Chiara Cirrito</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar />
        <Hero />
        <Social />
        <Form />
        <Footer />
      </main>
    </>
  );
}
