import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import Navbar from "@/components/navbar";
import Hero from "@/components/hero";
import Data from "@/components/data";
import SkillsTech from "@/components/skillsTech";
import Schools from "@/components/school";
import Projects from "@/components/projects/Projects";
import Footer from "@/components/footer";
import "@/styles/Home.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio Chiara Cirrito</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar />
        <Hero />
        <div className={styles.div}>
          <Data />
          <Schools />
        </div>

        <SkillsTech />
        <Projects />
        <Footer />
      </main>
    </>
  );
}
